# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# لغة الموقع (مهم لـ RTL لاحقًا)
lang: ar

# the direction of the webpage
#
# Available options:
#
#     ltr — use left to right direction (default)
#     rtl — use right to left direction
#
direction: rtl

# المنطقة الزمنية - اليمن
timezone: Asia/Aden

# إعدادات jekyll-seo-tag
# ↓ --------------------------

title: مدونة مود ويب
tagline: شروحات تقنية، أدوات ذكية، حلول يمن نت، وقوالب بلوجر

description: >-
  Modweeb is a professional Arabic tech blog offering Blogger templates, SEO tools, app reviews, YemenNet 4G solutions, and strategies for digital monetization.

# رابط الموقع
url: "https://modweeb.github.io"

github:
  username: modweeb

twitter:
  username: modweeb

social:
  name: Modweeb | مود ويب
  email: contact@modweeb.com
  links:
    - https://twitter.com/modweeb
    - https://github.com/modweeb
    - https://modweeb.com
    - https://t.me/modweeb

# Site Verification Settings
webmaster_verifications:
  google: "YOUR_GOOGLE_VERIFICATION_CODE"
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
  facebook: ""

# Web Analytics Settings
analytics:
  google:
    id: "G-XXXXXXXXXX"
  goatcounter:
    id: ""
  umami:
    id: ""
    domain: ""
  matomo:
    id: ""
    domain: ""
  cloudflare:
    id: ""
  fathom:
    id: ""

# Page views settings
pageviews:
  provider: ""

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
cdn: ""

# the avatar on sidebar
avatar: "https://i.postimg.cc/v8xt8V5n/web-app-manifest-512x512.png"

# Social preview image
social_preview_image: "https://i.postimg.cc/hG8bqpjm/modweeb-img-lo.jpg"

# Table of Contents in posts
toc: true

comments:
  provider: giscus
  giscus:
    repo: "modweeb/modweeb.github.io"
    repo_id: "REPO_ID_HERE"
    category: "Announcements"
    category_id: "CATEGORY_ID_HERE"
    mapping: "pathname"
    strict: false
    input_position: "bottom"
    lang: "ar"
    reactions_enabled: true

assets:
  self_host:
    enabled: false

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

baseurl: ""

# ------------ Advanced Settings (Not Recommended to Modify) -------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
    
